services:
  - type: web
    name: college-course-registration
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: DB_HOST
        value: mysql-5156455-trvaishnavi104-eedc.j.aivencloud.com
      - key: DB_PORT
        value: 10156
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: REPLACE_ON_RENDER
      - key: DB_NAME
        value: college_course_reg
      - key: DB_SSL_CA
        value: ca.pem
      - key: SECRET_KEY
        value: college_course_reg_secret_key_12345
      - key: FLASK_ENV
        value: production